### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by ada1582** [aodiwei/ChineseSampleSeq2SeqChatBot#1]
作者您好，打扰了，请问您有尝试过使用seq2seq模型来进行中文文本摘要（长文本）吗？
可不可以在您这个代码的基础上做中文文本摘要任务呀？求指导，O(∩_∩)O谢谢了！

**Comment by aodiwei** [comment]
@ada1582  文本摘要了解不是很多，但是思路应该都差不多，就是解码的时候生成摘要，最好使用attention的seq2seq,数据集的清洗和预处理上也要做好，比如对所有数字都统一为一个特殊词等。按理说，可以在我这个代码上改改可以用，主要的工作在训练集集处理上。有数据就好办，我是缺乏数据。

**Comment by ada1582** [comment]
O(∩_∩)O谢谢您的回答，我自己利用澎湃新闻网的长新闻及摘要构造了一个小型数据集，并利用如下的代码（TensorFlow1.7）进行模型构建和训练，但是训练的结果非常差，您能帮我看看代码的逻辑部分有什么问题吗（我自己查看了很久都没有发现什么问题，也有可能是数据集的清洗工作未到位）？

[chinese_textsum.zip](https://github.com/aodiwei/ChineseSampleSeq2SeqChatBot/files/1945282/chinese_textsum.zip)
