### ISSUE TITLE
训练完了怎么测试

### ISSUE THREAD

**Issue by zk0301** [aodiwei/ChineseSampleSeq2SeqChatBot#2]
测试方法啊大佬

**Comment by aodiwei** [comment]
@zk0301  请查看     [test 函数](https://github.com/aodiwei/ChineseSampleSeq2SeqChatBot/blob/722b61c9e2eb6e54405ec9350f55bee727be1412/model.py#L142)  model.py里已经有训练和测试代码，已经训练好后重载模型代码
